# Notebook 5 — Hyperparameter Optimization

## Objective

The baseline RT-DETR-L model achieved promising performance on the processed pothole dataset.

Although the baseline model demonstrated strong detection capability, several observations from the error analysis indicate room for improvement, particularly in detecting small potholes and increasing overall recall.

This notebook systematically investigates the effect of different hyperparameters on model performance.

Unlike arbitrary parameter tuning, each experiment modifies only a single training variable while keeping the remaining configuration identical to the baseline. This controlled approach enables objective evaluation of how individual hyperparameters influence detection accuracy and model generalization.

Each experiment will be compared against the baseline using identical evaluation metrics.

---

## Planned Experiments

| Experiment | Parameter Changed | Purpose |
|------------|------------------|----------|
| Baseline | None | Reference model |
| Experiment 1 | Image Size (640 → 800) | Improve small pothole detection |
| Experiment 2 | Epochs | Study convergence |
| Experiment 3 | Data Augmentation | Improve robustness |
| Experiment 4 | Learning Rate | Improve optimization |
| Experiment 5 | Best Combination | Final optimized model |

In [2]:
!pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.4.107-py3-none-any.whl.metadata (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.29.0)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python!=4.13.0.90,>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.13.0.92)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.10.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.25.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.35.2)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (13.595.45)
Collecting ultralytics-thop>=2.1.0 (from ultralytics)
  Downloading ultralytics_thop-2.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (26.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->ultralytics) (1.35.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2026.4.22)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.8.0->ultralytics) (1.5.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.4.107-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 24.8 MB/s eta 0:00:00a 0:00:01
Downloading ultralytics_thop-2.1.0-py3-none-any.whl (26 kB)
Installing collected packages: ultralytics-thop, ultralytics
Successfully installed ultralytics-8.4.107 ultralytics-thop-2.1.0

In [18]:
import os
import json
import yaml
import shutil
import random
import time

from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from ultralytics import RTDETR

## Experiment 1 — Higher Input Resolution

### Research Hypothesis

The exploratory data analysis revealed that a considerable proportion of potholes occupy a relatively small image area.

Increasing the input image resolution from **640×640** to **800×800** should provide the detector with finer spatial details, enabling improved localization of small potholes.

### Expected Outcome

- Higher Recall
- Higher mAP50-95
- Better localization

Potential drawbacks include:

- Increased GPU memory consumption
- Longer training time

In [19]:
# ============================================================
# Dataset Configuration
# ============================================================

from pathlib import Path
import yaml

# Path to Kaggle dataset
DATASET = Path(
    "/kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset"
)

yaml_path = DATASET / "dataset.yaml"

# Load original YAML
with open(yaml_path, "r") as f:
    cfg = yaml.safe_load(f)

# Update dataset root for current environment
cfg["path"] = str(DATASET)

# Save corrected YAML
FIXED_YAML = Path("/kaggle/working/dataset_fixed.yaml")

with open(FIXED_YAML, "w") as f:
    yaml.dump(cfg, f, sort_keys=False)

print("=" * 60)
print("Dataset configuration generated successfully.")
print("=" * 60)
print(f"Dataset Root : {DATASET}")
print(f"YAML File    : {FIXED_YAML}")
print("=" * 60)

============================================================
Dataset configuration generated successfully.
============================================================
Dataset Root : /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset
YAML File    : /kaggle/working/dataset_fixed.yaml
============================================================

In [20]:
# ============================================================
# Verify Dataset Configuration
# ============================================================

with open(FIXED_YAML) as f:
    print(f.read())

path: /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset
train: images/train
val: images/val
names:
  0: pothole

In [21]:
EXPERIMENT = {

    "experiment_name": "Exp01_ImageSize800",

    "model": "/kaggle/input/models/krishnatheachiever/rtdetr-baseline-experiment/pytorch/default/1/RTDETR_Baseline_Experiment/weights/best.pt",

    "data": str(FIXED_YAML),

    "epochs": 30,

    "imgsz": 800,

    "batch": 16,

    "optimizer": "AdamW",

    "lr0": 0.0005,

    "weight_decay": 0.0005,

    "workers": 4,

    "patience": 10,

    "device": 0,

    "seed": 42,

    "project": "RTDETR_Model_Refinement",

    "name": "Exp01_ImageSize800",

    "amp": True

}

In [22]:
pd.DataFrame(EXPERIMENT.items(), columns=["Parameter","Value"])

          Parameter                                              Value
0   experiment_name                                 Exp01_ImageSize800
1             model  /kaggle/input/models/krishnatheachiever/rtdetr...
2              data                 /kaggle/working/dataset_fixed.yaml
3            epochs                                                 30
4             imgsz                                                800
5             batch                                                 16
6         optimizer                                              AdamW
7               lr0                                             0.0005
8      weight_decay                                             0.0005
9           workers                                                  4
10         patience                                                 10
11           device                                                  0
12             seed                                                 42
13          project                            RTDETR_Model_Refinement
14             name                                 Exp01_ImageSize800
15              amp                                               True

## Training Configuration

Only the image resolution differs from the baseline.

All remaining parameters remain unchanged to ensure that performance differences can be attributed solely to the increase in input resolution.

In [23]:
model = RTDETR(EXPERIMENT["model"])

In [24]:
from ultralytics import RTDETR

model = RTDETR(EXPERIMENT["model"])

print("Loaded trained baseline model successfully.")

Loaded trained baseline model successfully.

## Model Training

The RT-DETR-L model is trained using the configuration defined for **Experiment 1**.

This experiment differs from the baseline only in the input image resolution (**640 → 800 pixels**). All other hyperparameters remain unchanged to ensure that any observed performance differences can be attributed solely to the increased input resolution.

During training, the framework automatically performs validation after each epoch, saves the best-performing model checkpoint, records training metrics, and generates visualizations required for subsequent evaluation.

In [25]:
# ============================================================
# Start Training
# ============================================================

import time

print("=" * 60)
print(f"Starting {EXPERIMENT['experiment_name']}")
print("=" * 60)

start_time = time.time()

results = model.train(

    data=EXPERIMENT["data"],

    epochs=EXPERIMENT["epochs"],

    imgsz=EXPERIMENT["imgsz"],

    batch=EXPERIMENT["batch"],

    optimizer=EXPERIMENT["optimizer"],

    lr0=EXPERIMENT["lr0"],

    weight_decay=EXPERIMENT["weight_decay"],

    workers=EXPERIMENT["workers"],

    patience=EXPERIMENT["patience"],

    device=EXPERIMENT["device"],

    seed=EXPERIMENT["seed"],

    amp=EXPERIMENT["amp"],

    project=EXPERIMENT["project"],

    name=EXPERIMENT["name"],

    verbose=True,

    plots=True,

    save=True,

    val=True,

    save_period=-1

)

end_time = time.time()

training_time = end_time - start_time

hours = int(training_time // 3600)
minutes = int((training_time % 3600) // 60)
seconds = int(training_time % 60)

print("\n" + "=" * 60)
print("Training Completed")
print("=" * 60)
print(f"Experiment       : {EXPERIMENT['experiment_name']}")
print(f"Training Time    : {hours:02d}:{minutes:02d}:{seconds:02d}")
print(f"Average/Epoch    : {training_time / EXPERIMENT['epochs']:.2f} sec")
print("=" * 60)

============================================================
Starting Exp01_ImageSize800
============================================================
Ultralytics 8.4.107 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/dataset_fixed.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=800, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.0005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/input/models/krishnatheachiever/rtdetr-baseline-experiment/pytorch/default/1/RTDETR_Baseline_Experiment/weights/best.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=Exp01_ImageSize800, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=RTDETR_Model_Refinement, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 16.1MB/s 0.0s
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]
 28        [21, 24, 27]  1   7303907  ultralytics.nn.modules.head.RTDETRDecoder    [1, [256, 256, 256]]
rt-detr-l summary: 470 layers, 32,808,131 parameters, 32,808,131 gradients, 108.0 GFLOPs

Transferred 941/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 68.2MB/s 0.1s
AMP: checks passed ✅
WARNING ⚠️ train: Slow image access detected (ping: 0.3±0.4 ms, read: 12.5±2.9 MB/s, size: 71.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels/train... 5000 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 5000/5000 252.6it/s 19.8s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels is not writable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
WARNING ⚠️ val: Slow image access detected (ping: 0.0±0.0 ms, read: 15.0±6.5 MB/s, size: 89.8 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels/val... 849 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 849/849 274.7it/s 3.1s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels is not writable, cache not saved.
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
Plotting labels to /kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800/labels.jpg...
Image sizes 800 train, 800 val
Using 2 dataloader workers
Logging results to /kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800
Starting training for 30 epochs...
WARNING ⚠️ CUDA out of memory with batch=16. Reducing to batch=8 and retrying (1/3).
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 176.9±151.1 MB/s, size: 112.2 KB)
train: Scanning /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels/train... 5000 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 5000/5000 1.2Kit/s 4.3s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels is not writable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.1±0.2 ms, read: 154.0±48.3 MB/s, size: 86.5 KB)
val: Scanning /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels/val... 849 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 849/849 1.1Kit/s 0.8s0.1ss
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels is not writable, cache not saved.
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
: 0% ──────────── 0/313  13.3s

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
WARNING ⚠️ CUDA backend memory error with batch=8. Reducing to batch=4 and retrying (2/3).
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 121.1±34.8 MB/s, size: 62.6 KB)
train: Scanning /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels/train... 5000 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 5000/5000 1.1Kit/s 4.5s0.0ss
WARNING ⚠️ train: Cache directory /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels is not writable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 115.5±20.7 MB/s, size: 69.7 KB)
val: Scanning /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels/val... 849 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 849/849 1.1Kit/s 0.8s0.1ss
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/krishnatheachiever/processed-pothole-yolo-dataset/labels is not writable, cache not saved.
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
: 0% ──────────── 0/625  9.0s

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       1/30       8.3G       0.56     0.4872     0.2306         14        800: 0% ──────────── 0/1250  4.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       1/30      8.46G      1.205     0.6739     0.5995         16        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:210.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.2s/it 31.7s1.1ss
                   all        849       2080      0.206      0.375      0.199     0.0734

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       2/30      4.67G     0.8584     0.9335     0.2833          9        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       2/30      4.69G     0.7459     0.8415     0.3111         22        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:140.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.388      0.444      0.353      0.142

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       3/30      5.38G     0.6925     0.8346     0.3811         11        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       3/30      5.38G     0.5992      0.885     0.2563         27        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:150.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.1s/it 28.4s1.1ss
                   all        849       2080       0.46      0.522      0.468       0.26

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       4/30      5.38G     0.6563      0.788     0.3311         22        800: 0% ──────────── 0/1250  0.6s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       4/30      5.38G     0.5348     0.8616     0.2311          8        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:130.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.1s/it 28.4s1.1ss
                   all        849       2080      0.486       0.55      0.486      0.283

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       5/30      5.38G     0.5951     0.7549     0.1872         23        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       5/30      5.38G      0.535     0.7791     0.2371         21        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:120.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.782      0.757      0.759      0.424

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       6/30      5.38G      0.611     0.7406     0.3145          7        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       6/30      5.38G     0.5506     0.7095     0.2499         20        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:120.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.785      0.712      0.755      0.412

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       7/30      5.38G     0.6727     0.5099     0.1883         13        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       7/30      5.38G     0.5423     0.7114     0.2537         12        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:100.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.814      0.706      0.749      0.421

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       8/30      5.38G      0.455      0.753     0.1874          7        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       8/30      5.38G     0.5536     0.6719     0.2566         26        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:110.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.784      0.733      0.754      0.429

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
       9/30      5.38G      0.609     0.8862     0.2712         12        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

       9/30      5.38G     0.5246     0.6643     0.2394         10        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:110.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.1s/it 28.4s1.1ss
                   all        849       2080      0.788      0.717      0.757      0.425

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      10/30      5.38G     0.4642     0.8349     0.2481         16        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      10/30      5.38G     0.5249     0.6958     0.2361         12        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:130.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.822      0.724       0.77      0.446

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      11/30      5.38G     0.5669      0.808       0.43          9        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      11/30      5.38G     0.5189     0.6612     0.2346         15        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:120.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.2s1.1ss
                   all        849       2080      0.816      0.743      0.776      0.454
      12/30      5.38G     0.2981     0.6585     0.1404          8        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      12/30      5.38G     0.5158     0.6438     0.2338         12        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:120.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.812      0.749       0.78      0.456

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      13/30      5.38G     0.3642     0.8533     0.1291          8        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      13/30      5.38G     0.5101     0.6421     0.2347          6        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:120.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.1s/it 28.5s1.1ss
                   all        849       2080      0.814      0.761      0.802      0.469

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      14/30      5.38G     0.5124     0.6414     0.2417         29        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      14/30      5.38G     0.5047     0.6334     0.2305         13        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:150.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.1s/it 28.4s1.1ss
                   all        849       2080      0.846       0.72      0.805       0.47

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      15/30      5.38G     0.5328     0.5815     0.1892         44        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      15/30      5.38G     0.5089     0.6129     0.2309         10        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:100.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.836      0.749      0.807      0.473

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      16/30      5.38G     0.5392     0.6497     0.2358          8        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      16/30      5.38G     0.4963     0.6212     0.2242         11        800: 100% ━━━━━━━━━━━━ 1250/1250 2.0it/s 10:100.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.835      0.742      0.805      0.482

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      17/30      5.38G      0.304     0.4557     0.2679          6        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      17/30      5.38G     0.4953     0.6003     0.2237          6        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:080.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.2s1.1ss
                   all        849       2080      0.827      0.755      0.812      0.486

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      18/30      5.38G     0.3852     0.4265     0.1573         18        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      18/30      5.38G     0.4901     0.5887      0.222         10        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:090.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.846       0.76      0.822      0.489

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      19/30      5.38G     0.3851     0.6744     0.1855          6        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      19/30      5.38G      0.488     0.5908     0.2224         24        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:080.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.2s1.1ss
                   all        849       2080      0.825      0.764      0.804      0.475

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      20/30      5.38G     0.5844     0.5727     0.1889         12        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      20/30      5.38G     0.4781     0.5928     0.2161          6        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:080.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.872      0.755      0.824      0.495
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      21/30      5.38G     0.3421     0.4941     0.1952         10        800: 0% ──────────── 0/1250  0.7s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      21/30      5.38G     0.4503     0.5513     0.2226          6        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:070.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.823      0.777      0.813      0.485

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      22/30      5.38G     0.5379     0.6051     0.1915         11        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      22/30      5.38G     0.4454     0.5325     0.2181          9        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:070.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.2s1.1ss
                   all        849       2080       0.84      0.771      0.819      0.495

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      23/30      5.38G     0.3958     0.4353    0.08205          7        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      23/30      5.38G     0.4391     0.5277     0.2173          4        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:070.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080       0.83      0.774      0.819      0.494

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      24/30      5.38G     0.6822      0.735     0.2487         21        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      24/30      5.38G     0.4323     0.5117     0.2138          9        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:080.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.2s1.1ss
                   all        849       2080      0.839      0.779      0.817      0.494

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      25/30      5.38G     0.4346     0.4141     0.1709         12        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      25/30      5.38G     0.4305     0.5065     0.2113          4        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:070.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.842      0.771      0.824      0.496

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      26/30      5.38G     0.5167     0.4032     0.2002          5        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      26/30      5.38G     0.4246     0.5002     0.2066          5        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:070.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.823      0.797      0.829      0.502

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      27/30      5.38G      0.563     0.3855     0.1592          5        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      27/30      5.38G     0.4176     0.4988     0.2044          4        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:060.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.833      0.794      0.821      0.499

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      28/30      5.38G     0.2253     0.4822      0.249          4        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      28/30      5.38G     0.4196     0.4977     0.2028          7        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:070.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.865      0.764      0.834      0.512

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      29/30      5.38G     0.5639     0.4402     0.2945          5        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      29/30      5.38G     0.4162     0.4878     0.2021         11        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:060.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080      0.844      0.786      0.822      0.503

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      30/30      5.38G     0.2243      0.428     0.2592          6        800: 0% ──────────── 0/1250  0.5s

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: grid_sampler_2d_backward_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:160.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

      30/30      5.38G     0.4155     0.4908     0.2029          5        800: 100% ━━━━━━━━━━━━ 1250/1250 2.1it/s 10:080.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0s/it 28.3s1.1ss
                   all        849       2080       0.85      0.786      0.835      0.508

30 epochs completed in 5.342 hours.
Optimizer stripped from /kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800/weights/last.pt, 66.3MB
Optimizer stripped from /kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800/weights/best.pt, 66.3MB

Validating /kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800/weights/best.pt...
Ultralytics 8.4.107 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
rt-detr-l summary: 315 layers, 31,985,795 parameters, 0 gradients, 103.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 27/27 1.0it/s 26.5s1.0ss
                   all        849       2080      0.862      0.768      0.831      0.511
Speed: 0.3ms preprocess, 27.1ms inference, 0.0ms loss, 0.2ms postprocess per image
Results saved to /kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800

============================================================
Training Completed
============================================================
Experiment       : Exp01_ImageSize800
Training Time    : 05:22:26
Average/Epoch    : 644.87 sec
============================================================

In [31]:
# ============================================================
# Experiment Output Directory
# ============================================================

from pathlib import Path

SAVE_DIR = Path(results.save_dir)

print("=" * 60)
print("Experiment Output Directory")
print("=" * 60)
print(SAVE_DIR)
print("=" * 60)

============================================================
Experiment Output Directory
============================================================
/kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800
============================================================

In [32]:
#Experiment Comparison Table
import pandas as pd

# ============================================================
# Master Experiment Comparison Table
# ============================================================

comparison_df = pd.DataFrame({

    "Stage": [
        "Baseline",
        "Exp01",
        "Exp02",
        "Exp03",
        "Exp04",
        "Final"
    ],

    "Starting Model": [
        "COCO Pretrained",
        "Baseline best.pt",
        "Exp01 best.pt",
        "Exp02 best.pt",
        "Exp03 best.pt",
        "Best Model"
    ],

    "Modification": [
        "Initial Training",
        "Image Size = 800",
        "Data Augmentation",
        "Learning Rate Fine-Tuning",
        "Additional Optimization",
        "Final Optimized Model"
    ],

    "Epochs": [
        75,
        30,
        20,
        20,
        20,
        "-"
    ],

    "Precision": [
        0.891,
        None,
        None,
        None,
        None,
        None
    ],

    "Recall": [
        0.792,
        None,
        None,
        None,
        None,
        None
    ],

    "mAP@50": [
        0.854,
        None,
        None,
        None,
        None,
        None
    ],

    "mAP@50-95": [
        0.541,
        None,
        None,
        None,
        None,
        None
    ],

    "Training Time": [
        "7h 24m",
        None,
        None,
        None,
        None,
        None
    ]

})

comparison_df

,Stage,Starting Model,Modification,Epochs,Precision,Recall,mAP@50,mAP@50-95,Training Time
0,Baseline,COCO Pretrained,Initial Training,75,0.891,0.792,0.854,0.541,7h 24m
1,Exp01,Baseline best.pt,Image Size = 800,30,NaN,NaN,NaN,NaN,None
2,Exp02,Exp01 best.pt,Data Augmentation,20,NaN,NaN,NaN,NaN,None
3,Exp03,Exp02 best.pt,Learning Rate Fine-Tuning,20,NaN,NaN,NaN,NaN,None
4,Exp04,Exp03 best.pt,Additional Optimization,20,NaN,NaN,NaN,NaN,None
5,Final,Best Model,Final Optimized Model,-,NaN,NaN,NaN,NaN,None

In [33]:
comparison_df.loc[
    comparison_df["Stage"] == "Exp01",
    [
        "Precision",
        "Recall",
        "mAP@50",
        "mAP@50-95",
        "Training Time"
    ]
] = [
    0.862,
    0.768,
    0.831,
    0.511,
    "5h 22m"
]

comparison_df

,Stage,Starting Model,Modification,Epochs,Precision,Recall,mAP@50,mAP@50-95,Training Time
0,Baseline,COCO Pretrained,Initial Training,75,0.891,0.792,0.854,0.541,7h 24m
1,Exp01,Baseline best.pt,Image Size = 800,30,0.862,0.768,0.831,0.511,5h 22m
2,Exp02,Exp01 best.pt,Data Augmentation,20,NaN,NaN,NaN,NaN,None
3,Exp03,Exp02 best.pt,Learning Rate Fine-Tuning,20,NaN,NaN,NaN,NaN,None
4,Exp04,Exp03 best.pt,Additional Optimization,20,NaN,NaN,NaN,NaN,None
5,Final,Best Model,Final Optimized Model,-,NaN,NaN,NaN,NaN,None

In [34]:
# ============================================================
# Save Comparison Table
# ============================================================

comparison_path = SAVE_DIR / "comparison_table.csv"

comparison_df.to_csv(
    comparison_path,
    index=False
)

print("Comparison table saved.")
print(comparison_path)

Comparison table saved.
/kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800/comparison_table.csv

In [35]:
# ============================================================
# Save Experiment Summary
# ============================================================

summary = f"""
============================================================
Experiment Summary
============================================================

Experiment Name : {EXPERIMENT['experiment_name']}

Starting Model  : Baseline best.pt

Modification    : Image Size = 800

Epochs          : {EXPERIMENT['epochs']}

Image Size      : {EXPERIMENT['imgsz']}

Precision       : 0.862

Recall          : 0.768

mAP50           : 0.831

mAP50-95        : 0.511

Training Time   : 5h 22m

============================================================
"""

summary_file = SAVE_DIR / "experiment_summary.txt"

with open(summary_file, "w") as f:
    f.write(summary)

print(summary)

============================================================
Experiment Summary
============================================================

Experiment Name : Exp01_ImageSize800

Starting Model  : Baseline best.pt

Modification    : Image Size = 800

Epochs          : 30

Image Size      : 800

Precision       : 0.862

Recall          : 0.768

mAP50           : 0.831

mAP50-95        : 0.511

Training Time   : 5h 22m

============================================================

In [36]:
# ============================================================
# Save Experiment Configuration
# ============================================================

import json

experiment_info = {

    "experiment": EXPERIMENT,

    "results": {

        "precision":0.862,

        "recall":0.768,

        "mAP50":0.831,

        "mAP50_95":0.511,

        "training_time":"5h 22m"

    }

}

with open(SAVE_DIR/"experiment.json","w") as f:

    json.dump(experiment_info,f,indent=4)

print("experiment.json saved.")

experiment.json saved.

In [37]:
# ============================================================
# Archive Experiment
# ============================================================

import shutil

zip_path = shutil.make_archive(

    str(SAVE_DIR),

    "zip",

    SAVE_DIR

)

print("="*60)
print("Experiment archived successfully.")
print("="*60)
print(zip_path)

============================================================
Experiment archived successfully.
============================================================
/kaggle/working/runs/detect/RTDETR_Model_Refinement/Exp01_ImageSize800.zip

In [38]:
# ============================================================
# Verify Archive
# ============================================================

from pathlib import Path

zip_file = Path(f"{SAVE_DIR}.zip")

print("Exists :", zip_file.exists())

print(
    "Size   :",
    round(zip_file.stat().st_size/(1024*1024),2),
    "MB"
)

Exists : True
Size   : 121.96 MB